name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare package (zip)
      run: |
        mkdir -p deploy_package
        tar --exclude='./deploy_package' -C . -cf - . | (cd deploy_package && tar -xf -)
        cd deploy_package
        zip -r ../package.zip .
          
    # - name: Build using AppService-Build
      # uses: azure/appservice-build@v2
      # with:
        # platform: python
        # platform-version: '3.12'
    - name: Disable server build on App Service (disable Oryx)
      run: |
        az webapp config appsettings set \
          --name "azmon-logs-agent-oren" \
          --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false
            
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'azmon-logs-agent-oren'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package.zip


    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'azmon-logs-agent-oren'
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
